In [1]:
import numpy as np

0\. Implement a function (whatever you want) and save it to a file (e.g. `function.py`). Import that file and use that function in this notebook.


In [2]:
from funcion import hello
hello()

Hello, world!


1\. Write the following as a list comprehension

In [3]:
# 1
ans = []
for i in range(3):
    for j in range(4):
        ans.append((i, j))
print (ans)

print([ (i,j) for j in range(4) for i in range(3)]) 

# 2
ans = map(lambda x: x*x, filter(lambda x: x%2 == 0, range(5)))
print (list(ans))

print([ x**2 for x in range(5) if x%2==0]) 



[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]
[(0, 0), (1, 0), (2, 0), (0, 1), (1, 1), (2, 1), (0, 2), (1, 2), (2, 2), (0, 3), (1, 3), (2, 3)]
[0, 4, 16]
[0, 4, 16]


2\. Convert the following function into a pure function with no global variables or side effects

In [ ]:
x = 5
def f(alist):
    for i in range(x):
         alist.append(i)
    return alist

alist = [1,2,3]
ans = f(alist)
print (ans)
print (alist) # alist has been changed!

def f2(alist,x=5):
  import copy
  new_list = copy.copy(alist) 
  for i in range(x):
    new_list.append(i)
  return new_list
ans2=f2(alist)
print(ans2)
print(alist)

3\. Write a `decorator` hello that makes every wrapped function print “Hello!”, i.e. something like:

```python
@hello
def square(x):
    return x*x
```



In [4]:
def hello(func):
    
    def wrapper(*args, **kwargs):
        print("Buona Giornata")
        func(*args)
    return wrapper 



@hello
def square(x):
    return x*x

print(square(2))

Buona Giornata
None


4\. Write the factorial function so that it a) does and b) does not use recursion.

In [ ]:
def factorial(n):
  if n==0:
    return 1
  else:
    return n*factorial(n-1)

def factorial2(n):
  x=1
  if n == 0:
    return x
  for i in range(n):
    x*=i
  return x

print(factorial2(0))

5\. Use HOFs (zip in particular) to compute the weight of a circle, a disk and a sphere, assuming different radii and different densities:

```python
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]
```

where the entries of the dictionary's values are the linear, superficial and volumetric densities of the materials respectively.

In particular define a list of three lambda functions using a comprehension that computes the circumference, the area and the volume for a given radius.


In [8]:
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]

sup = [lambda r: 2*np.pi*r, lambda r: np.pi*r**2, lambda r: 4/3*np.pi*r**3]

for e,dens in densities.items():
  for r,d in zip(radii,dens):
     mass=d*np.array([s(r) for s in sup] )
     print(mass)

[3.14159265 1.57079633 2.0943951 ]
[12.56637061 12.56637061 33.51032164]
[ 37.69911184  56.54866776 226.19467106]
[18.84955592  9.42477796 12.56637061]
[ 50.26548246  50.26548246 134.04128655]
[ 94.24777961 141.37166941 565.48667765]
[94.24777961 47.1238898  62.83185307]
[251.32741229 251.32741229 670.20643277]
[ 565.48667765  848.23001647 3392.92006588]


6\. Edit the class defintion to add an instance attribute of is_hungry = True to the Dog class. Then add a method called eat() which changes the value of is_hungry to False when called. Figure out the best way to feed each dog and then output “My dogs are hungry.” if all are hungry or “My dogs are not hungry.” if all are not hungry. The final output should look like this:

`I have 3 dogs. 
Tom is 6. 
Fletcher is 7. 
Larry is 9. 
And they're all mammals, of course. 
My dogs are not hungry.
`

```python
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
```

In [ ]:
class Dog:

    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age, is_hungry = True):
        self.name = name
        self.age = age
        self.is_hungry = is_hungry

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)
    

    def eat(self, eaten):
        if eaten:
           self.is_hungry = False 
        else:
           self.is_hungry = True

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)